// Solarized-dsh-theme — browser half (client plugin bundle).
//
// Loaded by dsh-client-modules at /plugins/@yuquexianzhou/solarized-dsh-theme/client.js and
// executed through the vendored cordis Loader's lazy-CJS module table
// (window.__ModuleLoader__.load). The factory body is plain CJS with
// require() resolved against the shell's module table — the same shape the
// shipped ui-* packages' tsdown bundles emit.
//
// Persistence note: the chosen theme is stored in localStorage. DSH's Host
// settings wire only exposes an allowlisted set of namespaces to browser
// clients (dsh-host-apiproxy's WEB_SETTINGS_NAMESPACES), so a third-party
// namespace would answer "settings-not-exposed"; the product itself keeps
// remote browser preferences process-local, and localStorage matches that
// boundary for a visual preference while surviving reloads on the same
// origin.
//
// Token tables are generated by scripts/gen-client.mjs from the Solarized
// (Ethan Schoonover, MIT) and Selenized (Jan Warchol, MIT) palettes; the
// key set mirrors the alias/specific/shiki sheets shipped by
// @deepseek-ai/dsh-client-ui-theme.
window.__ModuleLoader__.load({
	id: "@yuquexianzhou/solarized-dsh-theme",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
		let react_jsx_runtime = require("react/jsx-runtime");
		let _react = require("react");
		let _runtime_client = require("@deepseek-ai/dsh-client-runtime/client");

		//#region @yuquexianzhou/solarized-dsh-theme: definitions
		/** The settings row's locale namespace. */
		const SETTINGS_NS = "settings.solarized";
		/** localStorage key holding the selected theme id. */
		const STORAGE_KEY = "solarized-dsh-theme:theme";
		/** localStorage key remembering the last built-in preference. */
		const RESTORE_KEY = "solarized-dsh-theme:restore";
		/** Sentinel meaning "no custom theme — follow the built-in appearance". */
		const DEFAULT_THEME = "system";

		/**
		 * The four curated themes. Each is a third-party theme for the built-in
		 * ThemeRuntime: an id, the base palette it builds on (colorScheme drives
		 * body[data-ds-dark-theme]), and token overrides applied as inline
		 * custom properties on <body> by ui-layout's ThemePresenter. Values are
		 * concrete colors (no var() indirection); the --shiki-* entries restore
		 * the canonical Solarized/Selenized code palette in markdown code blocks.
		 */
		const THEMES = [
	{
		id: "solarized-dark",
		colorScheme: "dark",
		tokens: {
			"--dsw-alias-bg-base": "#002b36",
			"--dsw-alias-bg-layer-1": "#073642",
			"--dsw-alias-bg-layer-2": "#17414c",
			"--dsw-alias-bg-layer-3": "#234a54",
			"--dsw-alias-bg-mask-1": "rgba(0, 0, 0, 0.5)",
			"--dsw-alias-bg-mask-2": "rgba(0, 0, 0, 0.2)",
			"--dsw-alias-bg-mask-3": "rgba(0, 0, 0, 0.48)",
			"--dsw-alias-bg-mask-photo": "rgba(0, 0, 0, 0.88)",
			"--dsw-alias-bg-module-platform": "#04313c",
			"--dsw-alias-bg-multi-select": "#133e4a",
			"--dsw-alias-bg-overlay": "#1f4751",
			"--dsw-alias-bg-skeleton": "rgba(255, 255, 255, 0.08)",
			"--dsw-alias-border-inverted": "rgba(255, 255, 255, 0.06)",
			"--dsw-alias-border-inverted2": "rgba(255, 255, 255, 0.08)",
			"--dsw-alias-border-l1": "rgba(147, 161, 161, 0.14)",
			"--dsw-alias-border-l2-darkmode-thin": "rgba(147, 161, 161, 0.14)",
			"--dsw-alias-border-l2": "rgba(147, 161, 161, 0.26)",
			"--dsw-alias-border-l3": "rgba(147, 161, 161, 0.36)",
			"--dsw-alias-border-l4": "rgba(147, 161, 161, 0.5)",
			"--dsw-alias-brand-primary-invert": "#fdf6e3",
			"--dsw-alias-brand-primary-new-colorprimary-new-color": "#268bd2",
			"--dsw-static-deepseek-500": "#268bd2",
			"--dsw-static-deepseek-200": "#7db9e4",
			"--dsw-static-blue-450": "#268bd2",
			"--dsw-static-blue-500": "#268bd2",
			"--dsw-static-neutral-bluish-400": "#586e75",
			"--dsw-alias-brand-primary": "#268bd2",
			"--dsw-alias-brand-text": "#ffffff",
			"--dsw-alias-button-contrast-fill": "#586e75",
			"--dsw-alias-button-elevated-fill": "#04313c",
			"--dsw-alias-button-floating-fill": "#133e4a",
			"--dsw-alias-button-floating-hover": "#133e4a",
			"--dsw-alias-button-ghost-active-border": "rgba(131, 148, 150, 0.4)",
			"--dsw-alias-button-ghost-active-fill": "#17414c",
			"--dsw-alias-button-ghost-active-hover": "#1e4650",
			"--dsw-alias-button-info-fill": "#2aa198",
			"--dsw-alias-button-info-hover": "#44a19a",
			"--dsw-slz-sky": "#2aa198",
			"--dsw-slz-peach": "#cb4b16",
			"--dsw-slz-lavender": "#6c71c4",
			"--dsw-slz-blue": "#268bd2",
			"--dsw-alias-button-primary-dimmed": "#17414c",
			"--dsw-alias-button-primary-fill": "#268bd2",
			"--dsw-alias-button-primary-hover": "#4191c6",
			"--dsw-alias-button-tool-bar-fill": "rgba(88, 110, 117, 0.5)",
			"--dsw-alias-button-tool-bar-fill-invisible": "rgba(88, 110, 117, 0.36)",
			"--dsw-alias-button-tool-bar-hover": "rgba(88, 110, 117, 0.6)",
			"--dsw-alias-interactive-bg-active": "rgba(38, 139, 210, 0.2)",
			"--dsw-alias-interactive-bg-hover-accent": "rgba(38, 139, 210, 0.28)",
			"--dsw-alias-interactive-bg-hover-danger": "rgba(220, 50, 47, 0.15)",
			"--dsw-alias-interactive-bg-hover-solid": "#1b444f",
			"--dsw-alias-interactive-bg-hover": "rgba(38, 139, 210, 0.12)",
			"--dsw-alias-label-caption": "#586e75",
			"--dsw-alias-label-dimmed": "#586e75",
			"--dsw-alias-label-primary-bluish": "#789cad",
			"--dsw-alias-label-primary-dimmed": "#8b9b9c",
			"--dsw-alias-label-primary-foreground": "#002b36",
			"--dsw-alias-label-primary-inverted": "#002b36",
			"--dsw-alias-label-primary": "#93a1a1",
			"--dsw-alias-label-secondary": "#839496",
			"--dsw-alias-label-tertiary": "#657b83",
			"--dsw-alias-markdown-citation": "#1b444f",
			"--dsw-alias-markdown-code-block-banner": "#04323d",
			"--dsw-alias-markdown-code-block": "#00252e",
			"--dsw-alias-markdown-code-segment-selected": "#133e4a",
			"--dsw-alias-markdown-code-segment-unselected": "#0d3a46",
			"--dsw-alias-markdown-inline-code": "#073642",
			"--dsw-alias-markdown-placeholder": "#04313c",
			"--dsw-alias-markdown-tag": "#133e4a",
			"--dsw-alias-scrollbar-bg-l1": "#17414c",
			"--dsw-alias-scrollbar-bg-l2": "#1e4650",
			"--dsw-alias-scrollbar-hover-l1": "#2b4f59",
			"--dsw-alias-scrollbar-hover-l2": "#30525c",
			"--dsw-alias-state-business-primary": "#268bd2",
			"--dsw-alias-state-business-tertiary": "#17414c",
			"--dsw-alias-state-error-primary": "#dc322f",
			"--dsw-alias-state-error-secondary": "#ca4e4c",
			"--dsw-alias-state-success-primary": "#859900",
			"--dsw-alias-state-success-secondary": "#899b30",
			"--dsw-alias-state-success-tertiary": "#1a4538",
			"--dsw-alias-state-warn-label": "#b58900",
			"--dsw-alias-state-warn-primary": "#ae8e20",
			"--dsw-alias-state-warn-secondary": "#a99138",
			"--dsw-alias-state-warn-tertiary": "#1c403a",
			"--dsw-alias-toast-bg": "#1b444f",
			"--dsw-alias-tooltip-bg": "#234a54",
			"--dsw-specific-bubble": "#0a3f50",
			"--dsw-specific-bubble-highlight": "#0e4962",
			"--dsw-specific-input-major": "#073642",
			"--dsw-specific-login-input": "#0d3a46",
			"--dsw-specific-menu": "#234a54",
			"--dsw-specific-selector": "#0d3a46",
			"--dsw-specific-sidebar-fill": "#002b36",
			"--dsw-specific-sidebar-nav-item-active-accent": "#10506d",
			"--dsw-specific-sidebar-nav-item-active": "#1b444f",
			"--dsw-specific-sidebar-nav-item-hover": "#04323d",
			"--dsw-specific-tip": "#04313c",
			"--shiki-foreground": "#839496",
			"--shiki-background": "#00252e",
			"--shiki-token-constant": "#2aa198",
			"--shiki-token-string": "#2aa198",
			"--shiki-token-comment": "#586e75",
			"--shiki-token-keyword": "#859900",
			"--shiki-token-parameter": "#cb4b16",
			"--shiki-token-function": "#268bd2",
			"--shiki-token-string-expression": "#2aa198",
			"--shiki-token-punctuation": "#657b83",
			"--shiki-token-link": "#6c71c4",
		}
	},
	{
		id: "solarized-light",
		colorScheme: "light",
		tokens: {
			"--dsw-alias-bg-base": "#fdf6e3",
			"--dsw-alias-bg-layer-1": "#eee8d5",
			"--dsw-alias-bg-layer-2": "#e3dfcf",
			"--dsw-alias-bg-layer-3": "#dad8ca",
			"--dsw-alias-bg-mask-1": "rgba(0, 0, 0, 0.24)",
			"--dsw-alias-bg-mask-2": "rgba(0, 0, 0, 0.12)",
			"--dsw-alias-bg-mask-3": "rgba(0, 0, 0, 0.48)",
			"--dsw-alias-bg-mask-photo": "rgba(0, 0, 0, 0.88)",
			"--dsw-alias-bg-module-platform": "#f6efdc",
			"--dsw-alias-bg-multi-select": "#e7e2d1",
			"--dsw-alias-bg-overlay": "#dedbcc",
			"--dsw-alias-bg-skeleton": "rgba(0, 0, 0, 0.04)",
			"--dsw-alias-border-inverted": "rgba(0, 0, 0, 0)",
			"--dsw-alias-border-inverted2": "rgba(0, 0, 0, 0)",
			"--dsw-alias-border-l1": "rgba(101, 123, 131, 0.14)",
			"--dsw-alias-border-l2-darkmode-thin": "rgba(101, 123, 131, 0.2)",
			"--dsw-alias-border-l2": "rgba(101, 123, 131, 0.22)",
			"--dsw-alias-border-l3": "rgba(101, 123, 131, 0.32)",
			"--dsw-alias-border-l4": "rgba(101, 123, 131, 0.45)",
			"--dsw-alias-brand-primary-invert": "#002b36",
			"--dsw-alias-brand-primary-new-colorprimary-new-color": "#268bd2",
			"--dsw-static-deepseek-500": "#268bd2",
			"--dsw-static-deepseek-200": "#7db9e4",
			"--dsw-static-blue-450": "#268bd2",
			"--dsw-static-blue-500": "#268bd2",
			"--dsw-static-neutral-bluish-400": "#657b83",
			"--dsw-alias-brand-primary": "#268bd2",
			"--dsw-alias-brand-text": "#ffffff",
			"--dsw-alias-button-contrast-fill": "#93a1a1",
			"--dsw-alias-button-elevated-fill": "#fefbf4",
			"--dsw-alias-button-floating-fill": "#fefbf4",
			"--dsw-alias-button-floating-hover": "#fefaee",
			"--dsw-alias-button-ghost-active-border": "rgba(101, 123, 131, 0.35)",
			"--dsw-alias-button-ghost-active-fill": "#dedbcc",
			"--dsw-alias-button-ghost-active-hover": "#d7d6c8",
			"--dsw-alias-button-info-fill": "#2aa198",
			"--dsw-alias-button-info-hover": "#5fb6ab",
			"--dsw-slz-sky": "#2aa198",
			"--dsw-slz-peach": "#cb4b16",
			"--dsw-slz-lavender": "#6c71c4",
			"--dsw-slz-blue": "#268bd2",
			"--dsw-alias-button-primary-dimmed": "#e3dfcf",
			"--dsw-alias-button-primary-fill": "#268bd2",
			"--dsw-alias-button-primary-hover": "#4d9ed5",
			"--dsw-alias-button-tool-bar-fill": "rgba(101, 123, 131, 0.5)",
			"--dsw-alias-button-tool-bar-fill-invisible": "rgba(101, 123, 131, 0.36)",
			"--dsw-alias-button-tool-bar-hover": "rgba(101, 123, 131, 0.6)",
			"--dsw-alias-interactive-bg-active": "rgba(38, 139, 210, 0.16)",
			"--dsw-alias-interactive-bg-hover-accent": "rgba(38, 139, 210, 0.22)",
			"--dsw-alias-interactive-bg-hover-danger": "rgba(220, 50, 47, 0.06)",
			"--dsw-alias-interactive-bg-hover-solid": "#e3dfcf",
			"--dsw-alias-interactive-bg-hover": "rgba(38, 139, 210, 0.1)",
			"--dsw-alias-label-caption": "#657b83",
			"--dsw-alias-label-dimmed": "#d3d3c5",
			"--dsw-alias-label-primary-bluish": "#517283",
			"--dsw-alias-label-primary-dimmed": "#74888d",
			"--dsw-alias-label-primary-foreground": "#fdf6e3",
			"--dsw-alias-label-primary-inverted": "#fdf6e3",
			"--dsw-alias-label-primary": "#586e75",
			"--dsw-alias-label-secondary": "#657b83",
			"--dsw-alias-label-tertiary": "#839496",
			"--dsw-alias-markdown-citation": "#e3dfcf",
			"--dsw-alias-markdown-code-block-banner": "#e5e1d0",
			"--dsw-alias-markdown-code-block": "#e9e4d2",
			"--dsw-alias-markdown-code-segment-selected": "#fefbf4",
			"--dsw-alias-markdown-code-segment-unselected": "#e3dfcf",
			"--dsw-alias-markdown-inline-code": "#e7e2d1",
			"--dsw-alias-markdown-placeholder": "#f6efdc",
			"--dsw-alias-markdown-tag": "#e3dfcf",
			"--dsw-alias-scrollbar-bg-l1": "#dad8ca",
			"--dsw-alias-scrollbar-bg-l2": "#d7d6c8",
			"--dsw-alias-scrollbar-hover-l1": "#cbcdc1",
			"--dsw-alias-scrollbar-hover-l2": "#c5c8be",
			"--dsw-alias-state-business-primary": "#268bd2",
			"--dsw-alias-state-business-tertiary": "#d0dad5",
			"--dsw-alias-state-error-primary": "#dc322f",
			"--dsw-alias-state-error-secondary": "#e66d65",
			"--dsw-alias-state-success-primary": "#859900",
			"--dsw-alias-state-success-secondary": "#a3b039",
			"--dsw-alias-state-success-tertiary": "#e1dfbb",
			"--dsw-alias-state-warn-label": "#ad880d",
			"--dsw-alias-state-warn-primary": "#b58900",
			"--dsw-alias-state-warn-secondary": "#c7a439",
			"--dsw-alias-state-warn-tertiary": "#e7ddbb",
			"--dsw-alias-toast-bg": "#d7d6c8",
			"--dsw-alias-tooltip-bg": "#d3d3c5",
			"--dsw-specific-bubble": "#ecede2",
			"--dsw-specific-bubble-highlight": "#c6d5d4",
			"--dsw-specific-input-major": "#fdf6e3",
			"--dsw-specific-login-input": "#f6efdc",
			"--dsw-specific-menu": "#dad8ca",
			"--dsw-specific-selector": "#f6efdc",
			"--dsw-specific-sidebar-fill": "#eee8d5",
			"--dsw-specific-sidebar-nav-item-active-accent": "#d0dad5",
			"--dsw-specific-sidebar-nav-item-active": "#e3dfcf",
			"--dsw-specific-sidebar-nav-item-hover": "#e9e4d2",
			"--dsw-specific-tip": "#f6efdc",
			"--shiki-foreground": "#586e75",
			"--shiki-background": "#e9e4d2",
			"--shiki-token-constant": "#2aa198",
			"--shiki-token-string": "#2aa198",
			"--shiki-token-comment": "#93a1a1",
			"--shiki-token-keyword": "#859900",
			"--shiki-token-parameter": "#cb4b16",
			"--shiki-token-function": "#268bd2",
			"--shiki-token-string-expression": "#2aa198",
			"--shiki-token-punctuation": "#657b83",
			"--shiki-token-link": "#6c71c4",
		}
	},
	{
		id: "selenized-dark",
		colorScheme: "dark",
		tokens: {
			"--dsw-alias-bg-base": "#103c48",
			"--dsw-alias-bg-layer-1": "#184956",
			"--dsw-alias-bg-layer-2": "#2d5b69",
			"--dsw-alias-bg-layer-3": "#456b76",
			"--dsw-alias-bg-mask-1": "rgba(0, 0, 0, 0.5)",
			"--dsw-alias-bg-mask-2": "rgba(0, 0, 0, 0.2)",
			"--dsw-alias-bg-mask-3": "rgba(0, 0, 0, 0.48)",
			"--dsw-alias-bg-mask-photo": "rgba(0, 0, 0, 0.88)",
			"--dsw-alias-bg-module-platform": "#14434f",
			"--dsw-alias-bg-multi-select": "#235260",
			"--dsw-alias-bg-overlay": "#426974",
			"--dsw-alias-bg-skeleton": "rgba(255, 255, 255, 0.08)",
			"--dsw-alias-border-inverted": "rgba(255, 255, 255, 0.06)",
			"--dsw-alias-border-inverted2": "rgba(255, 255, 255, 0.08)",
			"--dsw-alias-border-l1": "rgba(173, 188, 188, 0.12)",
			"--dsw-alias-border-l2-darkmode-thin": "rgba(173, 188, 188, 0.12)",
			"--dsw-alias-border-l2": "rgba(173, 188, 188, 0.22)",
			"--dsw-alias-border-l3": "rgba(173, 188, 188, 0.32)",
			"--dsw-alias-border-l4": "rgba(173, 188, 188, 0.45)",
			"--dsw-alias-brand-primary-invert": "#cad8d9",
			"--dsw-alias-brand-primary-new-colorprimary-new-color": "#4695f7",
			"--dsw-static-deepseek-500": "#4695f7",
			"--dsw-static-deepseek-200": "#90bffa",
			"--dsw-static-blue-450": "#4695f7",
			"--dsw-static-blue-500": "#4695f7",
			"--dsw-static-neutral-bluish-400": "#72898f",
			"--dsw-alias-brand-primary": "#4695f7",
			"--dsw-alias-brand-text": "#ffffff",
			"--dsw-alias-button-contrast-fill": "#72898f",
			"--dsw-alias-button-elevated-fill": "#37626f",
			"--dsw-alias-button-floating-fill": "#35616e",
			"--dsw-alias-button-floating-hover": "#3b6471",
			"--dsw-alias-button-ghost-active-border": "rgba(173, 188, 188, 0.4)",
			"--dsw-alias-button-ghost-active-fill": "#3b6471",
			"--dsw-alias-button-ghost-active-hover": "#406874",
			"--dsw-alias-button-info-fill": "#41c7b9",
			"--dsw-alias-button-info-hover": "#63cbc1",
			"--dsw-slz-sky": "#41c7b9",
			"--dsw-slz-peach": "#ed8649",
			"--dsw-slz-lavender": "#af88eb",
			"--dsw-slz-blue": "#4695f7",
			"--dsw-alias-button-primary-dimmed": "#3b6471",
			"--dsw-alias-button-primary-fill": "#4695f7",
			"--dsw-alias-button-primary-hover": "#63a4f0",
			"--dsw-alias-button-tool-bar-fill": "rgba(114, 137, 143, 0.5)",
			"--dsw-alias-button-tool-bar-fill-invisible": "rgba(114, 137, 143, 0.36)",
			"--dsw-alias-button-tool-bar-hover": "rgba(114, 137, 143, 0.6)",
			"--dsw-alias-interactive-bg-active": "rgba(70, 149, 247, 0.2)",
			"--dsw-alias-interactive-bg-hover-accent": "rgba(70, 149, 247, 0.28)",
			"--dsw-alias-interactive-bg-hover-danger": "rgba(250, 87, 80, 0.15)",
			"--dsw-alias-interactive-bg-hover-solid": "#3e6773",
			"--dsw-alias-interactive-bg-hover": "rgba(70, 149, 247, 0.12)",
			"--dsw-alias-label-caption": "#72898f",
			"--dsw-alias-label-dimmed": "#426974",
			"--dsw-alias-label-primary-bluish": "#b0cbdf",
			"--dsw-alias-label-primary-dimmed": "#bccacb",
			"--dsw-alias-label-primary-foreground": "#103c48",
			"--dsw-alias-label-primary-inverted": "#103c48",
			"--dsw-alias-label-primary": "#cad8d9",
			"--dsw-alias-label-secondary": "#adbcbc",
			"--dsw-alias-label-tertiary": "#72898f",
			"--dsw-alias-markdown-citation": "#3b6471",
			"--dsw-alias-markdown-code-block-banner": "#14434f",
			"--dsw-alias-markdown-code-block": "#0e333d",
			"--dsw-alias-markdown-code-segment-selected": "#37626f",
			"--dsw-alias-markdown-code-segment-unselected": "#13414e",
			"--dsw-alias-markdown-inline-code": "#184956",
			"--dsw-alias-markdown-placeholder": "#14434f",
			"--dsw-alias-markdown-tag": "#37626f",
			"--dsw-alias-scrollbar-bg-l1": "#37626f",
			"--dsw-alias-scrollbar-bg-l2": "#3b6471",
			"--dsw-alias-scrollbar-hover-l1": "#496d78",
			"--dsw-alias-scrollbar-hover-l2": "#4c707a",
			"--dsw-alias-state-business-primary": "#4695f7",
			"--dsw-alias-state-business-tertiary": "#31647e",
			"--dsw-alias-state-error-primary": "#fa5750",
			"--dsw-alias-state-error-secondary": "#ee7772",
			"--dsw-alias-state-success-primary": "#75b938",
			"--dsw-alias-state-success-secondary": "#8fc268",
			"--dsw-alias-state-success-tertiary": "#386962",
			"--dsw-alias-state-warn-label": "#dbb32d",
			"--dsw-alias-state-warn-primary": "#dbb32d",
			"--dsw-alias-state-warn-secondary": "#d6be61",
			"--dsw-alias-state-warn-tertiary": "#476860",
			"--dsw-alias-toast-bg": "#3e6773",
			"--dsw-alias-tooltip-bg": "#456b76",
			"--dsw-specific-bubble": "#1d5166",
			"--dsw-specific-bubble-highlight": "#245c7e",
			"--dsw-specific-input-major": "#184956",
			"--dsw-specific-login-input": "#13414e",
			"--dsw-specific-menu": "#456b76",
			"--dsw-specific-selector": "#13414e",
			"--dsw-specific-sidebar-fill": "#103c48",
			"--dsw-specific-sidebar-nav-item-active-accent": "#326785",
			"--dsw-specific-sidebar-nav-item-active": "#3b6471",
			"--dsw-specific-sidebar-nav-item-hover": "#154450",
			"--dsw-specific-tip": "#14434f",
			"--shiki-foreground": "#adbcbc",
			"--shiki-background": "#0e333d",
			"--shiki-token-constant": "#41c7b9",
			"--shiki-token-string": "#75b938",
			"--shiki-token-comment": "#72898f",
			"--shiki-token-keyword": "#af88eb",
			"--shiki-token-parameter": "#ed8649",
			"--shiki-token-function": "#4695f7",
			"--shiki-token-string-expression": "#75b938",
			"--shiki-token-punctuation": "#72898f",
			"--shiki-token-link": "#dbb32d",
		}
	},
	{
		id: "selenized-light",
		colorScheme: "light",
		tokens: {
			"--dsw-alias-bg-base": "#fbf3db",
			"--dsw-alias-bg-layer-1": "#ece3cc",
			"--dsw-alias-bg-layer-2": "#d5cdb6",
			"--dsw-alias-bg-layer-3": "#c0bdac",
			"--dsw-alias-bg-mask-1": "rgba(0, 0, 0, 0.24)",
			"--dsw-alias-bg-mask-2": "rgba(0, 0, 0, 0.12)",
			"--dsw-alias-bg-mask-3": "rgba(0, 0, 0, 0.48)",
			"--dsw-alias-bg-mask-photo": "rgba(0, 0, 0, 0.88)",
			"--dsw-alias-bg-module-platform": "#f4ebd4",
			"--dsw-alias-bg-multi-select": "#e1d8c1",
			"--dsw-alias-bg-overlay": "#d6d1bf",
			"--dsw-alias-bg-skeleton": "rgba(0, 0, 0, 0.04)",
			"--dsw-alias-border-inverted": "rgba(0, 0, 0, 0)",
			"--dsw-alias-border-inverted2": "rgba(0, 0, 0, 0)",
			"--dsw-alias-border-l1": "rgba(83, 103, 109, 0.12)",
			"--dsw-alias-border-l2-darkmode-thin": "rgba(83, 103, 109, 0.18)",
			"--dsw-alias-border-l2": "rgba(83, 103, 109, 0.22)",
			"--dsw-alias-border-l3": "rgba(83, 103, 109, 0.32)",
			"--dsw-alias-border-l4": "rgba(83, 103, 109, 0.45)",
			"--dsw-alias-brand-primary-invert": "#fbf3db",
			"--dsw-alias-brand-primary-new-colorprimary-new-color": "#0072d4",
			"--dsw-static-deepseek-500": "#0072d4",
			"--dsw-static-deepseek-200": "#66aae5",
			"--dsw-static-blue-450": "#0072d4",
			"--dsw-static-blue-500": "#0072d4",
			"--dsw-static-neutral-bluish-400": "#909995",
			"--dsw-alias-brand-primary": "#0072d4",
			"--dsw-alias-brand-text": "#ffffff",
			"--dsw-alias-button-contrast-fill": "#53676d",
			"--dsw-alias-button-elevated-fill": "#fdf9ed",
			"--dsw-alias-button-floating-fill": "#fdf9ed",
			"--dsw-alias-button-floating-hover": "#fcf7e6",
			"--dsw-alias-button-ghost-active-border": "rgba(83, 103, 109, 0.35)",
			"--dsw-alias-button-ghost-active-fill": "#d6d1bf",
			"--dsw-alias-button-ghost-active-hover": "#d5d1be",
			"--dsw-alias-button-info-fill": "#009c8f",
			"--dsw-alias-button-info-hover": "#32ad9e",
			"--dsw-slz-sky": "#009c8f",
			"--dsw-slz-peach": "#c25d1e",
			"--dsw-slz-lavender": "#8762c6",
			"--dsw-slz-blue": "#0072d4",
			"--dsw-alias-button-primary-dimmed": "#d5cdb6",
			"--dsw-alias-button-primary-fill": "#0072d4",
			"--dsw-alias-button-primary-hover": "#2685d5",
			"--dsw-alias-button-tool-bar-fill": "rgba(83, 103, 109, 0.4)",
			"--dsw-alias-button-tool-bar-fill-invisible": "rgba(83, 103, 109, 0.3)",
			"--dsw-alias-button-tool-bar-hover": "rgba(83, 103, 109, 0.5)",
			"--dsw-alias-interactive-bg-active": "rgba(0, 114, 212, 0.16)",
			"--dsw-alias-interactive-bg-hover-accent": "rgba(0, 114, 212, 0.22)",
			"--dsw-alias-interactive-bg-hover-danger": "rgba(210, 33, 45, 0.06)",
			"--dsw-alias-interactive-bg-hover-solid": "#d5cdb6",
			"--dsw-alias-interactive-bg-hover": "rgba(0, 114, 212, 0.1)",
			"--dsw-alias-label-caption": "#909995",
			"--dsw-alias-label-dimmed": "#c0bdac",
			"--dsw-alias-label-primary-bluish": "#315366",
			"--dsw-alias-label-primary-dimmed": "#475a60",
			"--dsw-alias-label-primary-foreground": "#fbf3db",
			"--dsw-alias-label-primary-inverted": "#fbf3db",
			"--dsw-alias-label-primary": "#3a4d53",
			"--dsw-alias-label-secondary": "#53676d",
			"--dsw-alias-label-tertiary": "#909995",
			"--dsw-alias-markdown-citation": "#d5cdb6",
			"--dsw-alias-markdown-code-block-banner": "#e3dcc7",
			"--dsw-alias-markdown-code-block": "#e6dfc9",
			"--dsw-alias-markdown-code-segment-selected": "#fdf9ed",
			"--dsw-alias-markdown-code-segment-unselected": "#e1dac5",
			"--dsw-alias-markdown-inline-code": "#e1d8c1",
			"--dsw-alias-markdown-placeholder": "#f4ebd4",
			"--dsw-alias-markdown-tag": "#e1dac5",
			"--dsw-alias-scrollbar-bg-l1": "#d5d1be",
			"--dsw-alias-scrollbar-bg-l2": "#c0bdac",
			"--dsw-alias-scrollbar-hover-l1": "#c7c5b6",
			"--dsw-alias-scrollbar-hover-l2": "#c3c2b3",
			"--dsw-alias-state-business-primary": "#0072d4",
			"--dsw-alias-state-business-tertiary": "#d0d5cd",
			"--dsw-alias-state-error-primary": "#d2212d",
			"--dsw-alias-state-error-secondary": "#de6061",
			"--dsw-alias-state-success-primary": "#489100",
			"--dsw-alias-state-success-secondary": "#7eae42",
			"--dsw-alias-state-success-tertiary": "#d8d9b4",
			"--dsw-alias-state-warn-label": "#ad8900",
			"--dsw-alias-state-warn-primary": "#ad8900",
			"--dsw-alias-state-warn-secondary": "#c1a437",
			"--dsw-alias-state-warn-tertiary": "#e4d8b4",
			"--dsw-alias-toast-bg": "#d5d1be",
			"--dsw-alias-tooltip-bg": "#c0bdac",
			"--dsw-specific-bubble": "#ecebdb",
			"--dsw-specific-bubble-highlight": "#bdccce",
			"--dsw-specific-input-major": "#fbf3db",
			"--dsw-specific-login-input": "#f4ebd4",
			"--dsw-specific-menu": "#c0bdac",
			"--dsw-specific-selector": "#f4ebd4",
			"--dsw-specific-sidebar-fill": "#ece3cc",
			"--dsw-specific-sidebar-nav-item-active-accent": "#cbd3cd",
			"--dsw-specific-sidebar-nav-item-active": "#d5cdb6",
			"--dsw-specific-sidebar-nav-item-hover": "#e6dfc9",
			"--dsw-specific-tip": "#f4ebd4",
			"--shiki-foreground": "#53676d",
			"--shiki-background": "#e6dfc9",
			"--shiki-token-constant": "#009c8f",
			"--shiki-token-string": "#489100",
			"--shiki-token-comment": "#909995",
			"--shiki-token-keyword": "#8762c6",
			"--shiki-token-parameter": "#c25d1e",
			"--shiki-token-function": "#0072d4",
			"--shiki-token-string-expression": "#489100",
			"--shiki-token-punctuation": "#909995",
			"--shiki-token-link": "#ad8900",
		}
	},
		];

		/**
		 * Simplified Chinese dictionary (the key-set source of truth). Theme
		 * labels live under "theme.<id>" so the picker cards derive their key
		 * directly from the theme id — no id→key mapping to keep in sync.
		 */
		const zh = {
			"theme.title": "Solarized / Selenized 主题",
			"theme.default": "默认",
			"theme.solarized-dark": "Solarized 深色",
			"theme.solarized-light": "Solarized 浅色",
			"theme.selenized-dark": "Selenized 深色",
			"theme.selenized-light": "Selenized 浅色",
			"theme.checkUpdate": "检查更新",
			"theme.updating": "检查中…",
			"theme.updateError": "检查更新失败",
			"theme.updateCurrent": "当前",
			"theme.updateLatest": "最新",
			"theme.updateUpToDate": "已是最新版本"
		};

		/** English dictionary, checked complete against the zh key set. */
		const en = {
			"theme.title": "Solarized / Selenized themes",
			"theme.default": "Default",
			"theme.solarized-dark": "Solarized Dark",
			"theme.solarized-light": "Solarized Light",
			"theme.selenized-dark": "Selenized Dark",
			"theme.selenized-light": "Selenized Light",
			"theme.checkUpdate": "Check for updates",
			"theme.updating": "Checking…",
			"theme.updateError": "Update check failed",
			"theme.updateCurrent": "Current",
			"theme.updateLatest": "Latest",
			"theme.updateUpToDate": "You're up to date"
		};
		//#endregion

		//#region @yuquexianzhou/solarized-dsh-theme: persistence
		/** Read a localStorage string value (null on absence or error). */
		function readStorage(key) {
			try {
				const value = window.localStorage.getItem(key);
				return typeof value === "string" ? value : null;
			} catch {
				return null;
			}
		}

		/** Write (or remove with null) a localStorage value. */
		function writeStorage(key, value) {
			try {
				if (value === null) window.localStorage.removeItem(key);
				else window.localStorage.setItem(key, value);
			} catch {
				// storage unavailable / quota — the preference stays process-local
			}
		}

		/** Saved theme id (may be unknown/absent). */
		function readSavedTheme() {
			return readStorage(STORAGE_KEY);
		}

		/** Persist a theme choice; DEFAULT_THEME clears the stored value. */
		function writeSavedTheme(id) {
			writeStorage(STORAGE_KEY, id === DEFAULT_THEME ? null : id);
		}

		/**
		 * Remember a built-in preference (system/light/dark) whenever the
		 * runtime is not on one of our themes, so turning the theme off
		 * hands the user back exactly what they had before the plugin —
		 * instead of dropping them onto "system".
		 */
		function rememberBuiltinPreference(preference) {
			if (THEMES.some((themeDefinition) => themeDefinition.id === preference)) return;
			if (preference === "light" || preference === "dark" || preference === DEFAULT_THEME) {
				writeStorage(RESTORE_KEY, preference);
			}
		}

		/** The preference to restore when turning the theme off (default: system). */
		function readRestoredPreference() {
			const raw = readStorage(RESTORE_KEY);
			return raw === "light" || raw === "dark" ? raw : DEFAULT_THEME;
		}
		//#endregion

		//#region @yuquexianzhou/solarized-dsh-theme: settings row store
		/**
		 * Theme row slot store: a mirror of the theme service snapshot. The
		 * plugin's theme/change listener is the only writer; the row component
		 * reads via props.useStore.
		 */
		function createThemeStore() {
			return (0, _runtime_client.defineStore)({
				init: () => ({
					theme: "system",
					revision: -1
				}),
				actions: {
					sync: (d, theme, revision) => {
						if (revision <= d.revision) return;
						d.theme = theme;
						d.revision = revision;
					}
				}
			});
		}
		//#endregion

		//#region @yuquexianzhou/solarized-dsh-theme: settings row
		/** Inline style sheet for the row (kept dependency-free). */
		const styles = {
			group: {
				borderBottom: "1px solid var(--dsw-alias-border-l2)",
				display: "flex",
				flexDirection: "column",
				gap: "10px",
				padding: "16px 0"
			},
			title: {
				color: "var(--dsw-alias-label-primary)",
				fontSize: "14px",
				fontWeight: 400,
				lineHeight: "22px"
			},
			grid: {
				display: "flex",
				flexWrap: "wrap",
				gap: "10px"
			},
			card: {
				display: "flex",
				flexDirection: "column",
				alignItems: "center",
				gap: "6px",
				width: "96px",
				padding: "3px",
				borderRadius: "10px",
				// Longhands, not the border shorthand: React removes borderColor
				// on deselect, and with the shorthand gone too the remaining
				// width/style fall back to currentColor (black/white border).
				borderWidth: "2px",
				borderStyle: "solid",
				borderColor: "transparent",
				background: "transparent",
				cursor: "pointer",
				font: "inherit",
				boxSizing: "border-box"
			},
			cardSelected: {
				borderColor: "var(--dsw-alias-brand-primary)",
				background: "var(--dsw-alias-interactive-bg-hover)"
			},
			cardLabel: {
				color: "var(--dsw-alias-label-secondary)",
				fontSize: "12px",
				lineHeight: "16px",
				whiteSpace: "nowrap"
			},
			cardLabelSelected: {
				color: "var(--dsw-alias-label-primary)"
			},
			swatch: {
				width: "100%",
				height: "52px",
				borderRadius: "8px",
				boxSizing: "border-box",
				padding: "8px",
				display: "flex",
				flexDirection: "column",
				justifyContent: "center",
				gap: "6px"
			},
			swatchLine: {
				height: "7px",
				borderRadius: "4px"
			},
			defaultSwatch: {
				width: "100%",
				height: "52px",
				borderRadius: "8px",
				boxSizing: "border-box",
				display: "flex",
				overflow: "hidden",
				border: "1px solid var(--dsw-alias-border-l2)"
			},
			updateRow: {
				display: "flex",
				alignItems: "center",
				flexWrap: "wrap",
				gap: "8px",
				marginTop: "4px"
			},
			updateButton: {
				background: "var(--dsw-alias-button-floating-fill)",
				border: "1px solid var(--dsw-alias-border-l2)",
				borderRadius: "8px",
				color: "var(--dsw-alias-label-primary)",
				cursor: "pointer",
				font: "inherit",
				fontSize: "12px",
				lineHeight: "18px",
				padding: "3px 10px"
			},
			updateDetail: {
				color: "var(--dsw-alias-label-secondary)",
				fontSize: "12px",
				lineHeight: "18px"
			},
			updateCommand: {
				background: "var(--dsw-alias-markdown-code-block)",
				borderRadius: "6px",
				color: "var(--dsw-alias-label-primary)",
				fontFamily: "var(--ds-font-family-code)",
				fontSize: "11px",
				padding: "2px 8px",
				wordBreak: "break-all"
			}
		};

		/** Mini palette preview driven by one theme's token table. */
		function ThemeSwatch({ tokens }) {
			return (0, react_jsx_runtime.jsxs)("div", {
				style: {
					...styles.swatch,
					background: tokens["--dsw-alias-bg-layer-1"],
					border: "1px solid " + tokens["--dsw-alias-border-l2"]
				},
				children: [
					(0, react_jsx_runtime.jsx)("div", {
						style: {
							...styles.swatchLine,
							width: "70%",
							background: tokens["--dsw-alias-label-primary"],
							opacity: 0.85
						}
					}),
					(0, react_jsx_runtime.jsx)("div", {
						style: {
							...styles.swatchLine,
							width: "45%",
							background: tokens["--dsw-alias-brand-primary"]
						}
					}),
					(0, react_jsx_runtime.jsx)("div", {
						style: {
							...styles.swatchLine,
							width: "55%",
							background: tokens["--dsw-alias-label-secondary"],
							opacity: 0.55
						}
					})
				]
			});
		}

		/** "Default" chip: follow the built-in appearance (light + dark halves). */
		function DefaultSwatch() {
			return (0, react_jsx_runtime.jsxs)("div", {
				style: styles.defaultSwatch,
				children: [
					(0, react_jsx_runtime.jsx)("div", { style: { flex: 1, background: "#f4f4f5" } }),
					(0, react_jsx_runtime.jsx)("div", { style: { flex: 1, background: "#1c1c20" } })
				]
			});
		}

		/** One selectable theme card. */
		function ThemeCard({ theme, selected, onSelect, t }) {
			return (0, react_jsx_runtime.jsxs)("button", {
				type: "button",
				onClick: onSelect,
				"aria-pressed": selected,
				style: {
					...styles.card,
					...(selected ? styles.cardSelected : {})
				},
				children: [
					(0, react_jsx_runtime.jsx)(ThemeSwatch, { tokens: theme.tokens }),
					(0, react_jsx_runtime.jsx)("span", {
						style: {
							...styles.cardLabel,
							...(selected ? styles.cardLabelSelected : {})
						},
						children: t("theme." + theme.id)
					})
				]
			});
		}

		/**
		 * Update-check row: silently checks once when the settings row
		 * mounts (host /solarized/check-update route, npm registry, 5-min
		 * cache), showing current/latest versions and the copyable upgrade
		 * command when a newer release exists — plus a manual "check for
		 * updates" button. The mount check renders nothing until the result
		 * lands, so opening Settings never flickers.
		 */
		function UpdateRow({ t }) {
			const [state, setState] = _react.useState({ idle: true });
			const check = (fromClick) => {
				if (fromClick) setState({ loading: true });
				fetch("/solarized/check-update")
					.then((response) => (response.ok ? response.json() : Promise.reject(new Error("HTTP " + response.status))))
					.then((payload) => setState(payload))
					.catch((error) => setState({ error: error instanceof Error ? error.message : String(error) }));
			};
			_react.useEffect(() => {
				check(false);
			}, []);
			let detail = null;
			if (state.loading) detail = t("theme.updating");
			else if (state.error) detail = t("theme.updateError") + " (" + state.error + ")";
			else if (state.ok === false) detail = t("theme.updateError") + " (" + (state.error ?? "") + ")";
			else if (state.upToDate) detail = t("theme.updateUpToDate") + " · " + t("theme.updateCurrent") + " " + state.current;
			else if (state.latest) detail = t("theme.updateCurrent") + " " + state.current + " → " + t("theme.updateLatest") + " " + state.latest;
			return (0, react_jsx_runtime.jsxs)("div", {
				style: styles.updateRow,
				children: [
					(0, react_jsx_runtime.jsx)("button", {
						type: "button",
						onClick: () => check(true),
						style: styles.updateButton,
						children: t("theme.checkUpdate")
					}),
					detail !== null ? (0, react_jsx_runtime.jsx)("span", {
						style: styles.updateDetail,
						children: detail
					}) : null,
					state.ok === true && state.upToDate === false && state.latest ? (0, react_jsx_runtime.jsx)("code", {
						style: styles.updateCommand,
						children: state.command
					}) : null
				]
			});
		}

		/**
		 * Theme picker row registered into the Settings → General item slot,
		 * right after the built-in Appearance row: title + a "Default" chip and
		 * one swatch card per curated theme.
		 */
		function ThemeRow({ t, setTheme, useStore }) {
			const theme = useStore((s) => s.theme);
			const selected = THEMES.some((candidate) => candidate.id === theme) ? theme : null;
			return (0, react_jsx_runtime.jsxs)("div", {
				style: styles.group,
				children: [
					(0, react_jsx_runtime.jsx)("div", {
						style: styles.title,
						children: t("theme.title")
					}),
					(0, react_jsx_runtime.jsxs)("div", {
						style: styles.grid,
						children: [
							(0, react_jsx_runtime.jsxs)("button", {
								type: "button",
								onClick: () => setTheme(DEFAULT_THEME),
								"aria-pressed": selected === null,
								style: {
									...styles.card,
									...(selected === null ? styles.cardSelected : {})
								},
								children: [
									(0, react_jsx_runtime.jsx)(DefaultSwatch, {}),
									(0, react_jsx_runtime.jsx)("span", {
										style: {
											...styles.cardLabel,
											...(selected === null ? styles.cardLabelSelected : {})
										},
										children: t("theme.default")
									})
								]
							}),
							THEMES.map((themeDefinition) => (0, react_jsx_runtime.jsx)(ThemeCard, {
								theme: themeDefinition,
								selected: selected === themeDefinition.id,
								onSelect: () => setTheme(themeDefinition.id),
								t
							}, themeDefinition.id))
						]
					}),
					(0, react_jsx_runtime.jsx)(UpdateRow, { t })
				]
			});
		}
		//#endregion

		//#region @yuquexianzhou/solarized-dsh-theme: client plugin body
		/**
		 * Required services: theme runtime (registration and switching), the
		 * settings slot and locale (the picker row). Persistence is
		 * localStorage, so no settings transport is needed.
		 */
		const inject = [
			"slots",
			"locale",
			"theme"
		];

		/**
		 * Client plugin body: register the four themes into the theme runtime,
		 * restore the saved theme, keep the row store in sync with
		 * theme/change, and register the picker row into Settings → General.
		 * @param ctx - client cordis context.
		 */
		function apply(ctx) {
			const disposers = THEMES.map((themeDefinition) => ctx.theme.register(themeDefinition));
			ctx.effect(() => () => {
				for (const dispose of disposers) dispose();
			}, "@yuquexianzhou/solarized-dsh-theme: theme registration");

			// Component-level color accents, mirroring dsh-catppuccin: user
			// bubble tint, composer + button, tool call labels, timestamps,
			// sidebar hovers, homepage gradient and more. Selectors are
			// boosted with :not(#dsh-solarized) to out-rank the shipped
			// ui-* sheets (injected after ours at equal specificity), and
			// the whole sheet mounts only while one of our themes is
			// active — the Default preference stays pixel-identical.
			const boost = (selector) =>
				selector.split(",").map((part) => `${part.trim()}:not(#dsh-solarized)`).join(",");
			const SURFACE_RULES = [
				[
					'[class$="_userStack"] [class$="_bubble"]',
					'  background: color-mix(in srgb, var(--dsw-alias-brand-primary) 40%, var(--dsw-alias-bg-layer-2));'
				],
				// light flavors (solarized-light / selenized-light) tint at
				// 30%: the pale surface makes 40% look stronger
				[
					'body:not([data-ds-dark-theme]) [class$="_userStack"] [class$="_bubble"]',
					'  background: color-mix(in srgb, var(--dsw-alias-brand-primary) 30%, var(--dsw-alias-bg-layer-2));'
				],
				[
					'button[class$="_add"][aria-haspopup="listbox"]',
					'  color: var(--dsw-slz-sky);'
				],
				[
					'[class$="_refChip"]',
					'  background: color-mix(in srgb, var(--dsw-alias-brand-primary) 22%, transparent);'
				],
				[
					'[class$="_thinkBody"]',
					'  color: color-mix(in srgb, var(--dsw-slz-peach) 72%, var(--dsw-alias-label-tertiary));'
				],
				[
					'[class$="_QWLzlG_title"]',
					'  color: var(--dsw-slz-peach);'
				],
				[
					'[class$="_o3BgMG_title"]',
					'  color: var(--dsw-slz-sky);'
				],
				[
					'[class$="_infostring"]',
					'  color: var(--dsw-slz-peach);'
				],
				[
					'[class$="_timeStart"]',
					'  color: var(--dsw-slz-lavender);'
				],
				[
					'[class$="o3BgMG_summary"]',
					'  color: color-mix(in srgb, var(--dsw-slz-sky) 55%, var(--dsw-alias-label-tertiary));'
				],
				[
					'[class$="QWLzlG_summary"]',
					'  color: color-mix(in srgb, var(--dsw-slz-peach) 55%, var(--dsw-alias-label-tertiary));'
				],
				[
					'[class$="_title_9cl6j_64"]:not([class$="QWLzlG_title"]):not([class$="o3BgMG_title"])',
					'  color: var(--dsw-slz-blue);'
				],
				[
					'[class*="_copyButton"]:hover',
					'  color: var(--dsw-alias-brand-primary);'
				],
				[
					'[class$="p-xYUq_actions"] button:hover, [class$="Sxvs8a_actions"] button:hover, [class$="_7yHdaG_actions"] button:hover, [class$="osXY9a_actions"] button:hover',
					'  color: var(--dsw-alias-brand-primary);'
				],
				[
					'[class$="YDXeBa_selected"] [class$="YDXeBa_title"]',
					'  color: var(--dsw-alias-brand-primary);'
				],
				[
					'[class$="YDXeBa_title"]:hover',
					'  color: var(--dsw-alias-brand-primary);'
				],
				[
					'[class$="YDXeBa_time"]',
					'  color: var(--dsw-slz-lavender);'
				],
				[
					'[class~="hHd-Xa_newSessionLabel"]:hover',
					'  color: var(--dsw-alias-brand-primary);'
				],
				[
					'[class~="hHd-Xa_iconButton"]:hover, [class~="qDHVXG_iconButton"]:hover, [class~="qDHVXG_searchButton"]:hover, [class~="YDXeBa_iconButton"]:hover',
					'  color: var(--dsw-alias-brand-primary);'
				],
				[
					'[class~="VOzbGW_trigger"]:hover',
					'  color: var(--dsw-alias-brand-primary);'
				],
				[
					'[class$="wSkVaW_crumbCurrent"]',
					'  color: var(--dsw-alias-brand-primary);'
				],
				[
					'[class$="pXSMma_headlineText"]',
					[
						'  background: linear-gradient(90deg, var(--dsw-slz-peach), var(--dsw-slz-sky), var(--dsw-alias-brand-primary));',
						'  -webkit-background-clip: text;',
						'  background-clip: text;',
						'  -webkit-text-fill-color: transparent;',
						'  color: transparent;'
					].join('\n')
				],
				[
					'[class$="pXSMma_workspaceLabel"]',
					'  color: var(--dsw-slz-lavender);'
				],
				[
					'[class$="pXSMma_previewBadge"]',
					'  color: var(--dsw-alias-state-warn-label);'
				],
				[
					'[class$="_7KE1Ra_triggerEffort"]',
					'  color: var(--dsw-slz-lavender);'
				],
				[
					'[class$="Sh0Q9G_triggerLabel"]:hover, [class$="_7KE1Ra_triggerLabel"]:hover',
					'  color: var(--dsw-alias-brand-primary);'
				],
				[
					'[class$="_7KE1Ra_option"]:hover:not(:disabled), [class$="mufS8W_row"]:hover',
					'  color: var(--dsw-alias-brand-primary);'
				],
				[
					'[class$="uV2eYG_card"]:hover',
					'  border-color: color-mix(in srgb, var(--dsw-alias-brand-primary) 55%, transparent);'
				],
				[
					'[class$="uV2eYG_primary"]:hover',
					'  filter: brightness(1.08);'
				],
				[
					'[class$="uV2eYG_primary"]:is([aria-label="停止"],[aria-label="Stop"])',
					[
						'  background: var(--dsw-alias-state-error-primary);',
						'  filter: none;'
					].join('\n')
				]
			].map(([selector, body]) => `${boost(selector)} {\n${body}\n}`).join("\n");
			const style = document.createElement("style");
			style.textContent = SURFACE_RULES;
			const syncSurfaceTint = () => {
				const active = THEMES.some((themeDefinition) => themeDefinition.id === ctx.theme.getTheme().preference);
				if (active && !style.isConnected) document.head.appendChild(style);
				if (!active && style.isConnected) style.remove();
			};
			syncSurfaceTint();
			ctx.on("theme/change", syncSurfaceTint);
			ctx.effect(() => () => {
				style.remove();
			}, "@yuquexianzhou/solarized-dsh-theme: surface tint lifecycle");

			// Restore the saved theme. The ThemeService adopts its durable
			// built-in preference from the Host settings scope asynchronously
			// after boot, and re-adopts it on every settings-document reload
			// — switching a model rewrites the settings doc and clobbers our
			// third-party preference back to the document's value ("system"
			// when never written, or a persisted light/dark). So instead of
			// a one-shot boot window, defend on every theme/change.
			//
			// The one seam that tells "the user clicked light/dark in the
			// Appearance row THIS session" apart from "adopt() copied the
			// settings document at boot/reload" is the setTheme wrapper:
			// adopt() writes the runtime preference directly and never goes
			// through setTheme. A built-in preference only wins while it
			// matches a live explicit pick; values adopted from the document
			// (livePick null) are stale for us — the theme row choice is
			// newer than the document's light/dark — so the theme is
			// re-applied then. Picking a theme clears the record.
			let liveBuiltinPick = null;
			const originalSetTheme = ctx.theme.setTheme;
			ctx.theme.setTheme = (id) => {
				liveBuiltinPick = id === "light" || id === "dark" || id === DEFAULT_THEME ? id : null;
				originalSetTheme.call(ctx.theme, id);
			};
			const reassertSaved = () => {
				const current = ctx.theme.getTheme().preference;
				if ((current === "light" || current === "dark") && current === liveBuiltinPick) return;
				const latest = readSavedTheme();
				if (typeof latest === "string" && latest !== DEFAULT_THEME && THEMES.some((themeDefinition) => themeDefinition.id === latest)) {
					ctx.theme.setTheme(latest);
				}
			};
			reassertSaved();

			// Durable two-layer persistence: localStorage is the instant
			// layer, the host's solarized-state.json (under $DSH_HOME)
			// survives Desktop's per-launch port churn where localStorage
			// always starts empty. Hydrate once at boot when localStorage
			// has no choice, then debounce-flush every change to the file.
			const STATE_ROUTE = "/solarized/state";
			let stateTimer = null;
			const flushState = () => {
				const saved = readSavedTheme();
				fetch(STATE_ROUTE, {
					method: "PUT",
					headers: { "content-type": "application/json" },
					body: JSON.stringify({ version: 1, theme: saved })
				}).catch(() => {
					// best-effort; localStorage still holds the choice
				});
			};
			const scheduleFlush = () => {
				if (stateTimer !== null) clearTimeout(stateTimer);
				stateTimer = setTimeout(() => {
					stateTimer = null;
					flushState();
				}, 300);
			};
			const hydrateFromFile = async () => {
				if (readSavedTheme() !== null) return;
				try {
					const response = await fetch(STATE_ROUTE);
					if (!response.ok) return;
					const state = await response.json();
					const theme = state && typeof state.theme === "string" && THEMES.some((themeDefinition) => themeDefinition.id === state.theme) ? state.theme : null;
					if (theme !== null) {
						writeSavedTheme(theme);
						if (ctx.theme.getTheme().preference === DEFAULT_THEME) ctx.theme.setTheme(theme);
					}
				} catch {
					// route absent (older host) — localStorage-only mode
				}
			};
			hydrateFromFile();

			const themeStore = createThemeStore();
			let themeBound;
			const syncTheme = (snapshot) => {
				themeBound?.sync(snapshot.preference, snapshot.revision);
			};
			ctx.on("theme/change", (snapshot) => {
				syncTheme(snapshot);
				const pref = snapshot.preference;
				// Record the built-in preference on every non-theme
				// observation (boot, adopt() reloads, explicit Appearance
				// changes) BEFORE any re-assert, so turning the theme off
				// can hand the user back exactly what they had.
				rememberBuiltinPreference(pref);
				// If the preference moved to another plugin's third-party theme,
				// drop our stored choice so only the last-picked plugin restores
				// at boot (both plugins must implement this convention).
				if (pref !== DEFAULT_THEME && pref !== "light" && pref !== "dark" && !THEMES.some((themeDefinition) => themeDefinition.id === pref)) {
					writeSavedTheme(DEFAULT_THEME);
				}
				// Re-assert from a fresh task: a re-entrant setTheme inside the
				// dispatch is missed by other subscribers (ui-layout's
				// ThemePresenter), so the restored theme would never reach the DOM.
				scheduleFlush();
				setTimeout(() => {
					reassertSaved();
				}, 0);
			});

			ctx.effect(() => ctx.locale.register(SETTINGS_NS, {
				zh,
				en
			}), "@yuquexianzhou/solarized-dsh-theme: settings row dictionaries");

			const themeInjected = (actions) => {
				themeBound = actions;
				syncTheme(ctx.theme.getTheme());
				return {
					setTheme: (id) => {
						// persist first: setTheme publishes a synchronous
						// theme/change, so the re-assert handler must already
						// see the new saved value (otherwise toggling back to
						// the default re-applies the old theme)
						writeSavedTheme(id);
						// turning the theme off restores the user's last
						// built-in preference instead of forcing "system"
						ctx.theme.setTheme(id === DEFAULT_THEME ? readRestoredPreference() : id);
						scheduleFlush();
					}
				};
			};
			ctx.slots.inject("settings.general.item", () => ctx.slots.register({
				name: "settings.general.item",
				id: "solarized",
				order: 20,
				store: themeStore,
				locale: SETTINGS_NS,
				inject: themeInjected
			}, ThemeRow));

			ctx.effect(() => () => {
				if (stateTimer !== null) clearTimeout(stateTimer);
				// undo the setTheme wrapper so a stopped plugin leaves the
				// runtime as it found it
				ctx.theme.setTheme = originalSetTheme;
			}, "@yuquexianzhou/solarized-dsh-theme: state flush timer");
		}
		//#endregion

		exports.SETTINGS_NS = SETTINGS_NS;
		exports.THEMES = THEMES;
		exports.DEFAULT_THEME = DEFAULT_THEME;
		exports.apply = apply;
		exports.inject = inject;
		return module.exports;
	}
});
