// dsh-Solarized — browser half (client plugin bundle).
//
// Loaded by dsh-client-modules at /plugins/dsh-solarized/client.js and
// executed through the vendored cordis Loader's lazy-CJS module table
// (window.__ModuleLoader__.load). The factory body is plain CJS with
// require() resolved against the shell's module table — the same shape the
// shipped ui-* packages' tsdown bundles emit.
//
// Persistence note: the chosen theme is stored in localStorage. DSH's Host
// settings wire only exposes an allowlisted set of namespaces to browser
// clients (dsh-host-apiproxy's WEB_SETTINGS_NAMESPACES), so a third-party
// namespace would answer "settings-not-exposed"; the product itself keeps
// remote browser preferences process-local, and localStorage matches that
// boundary for a visual preference while surviving reloads on the same
// origin.
//
// Token tables are generated by scripts/gen-client.mjs from the Solarized
// (Ethan Schoonover, MIT) and Selenized (Jan Warchol, MIT) palettes; the
// key set mirrors the alias/specific/shiki sheets shipped by
// @deepseek-ai/dsh-client-ui-theme.
window.__ModuleLoader__.load({
	id: "dsh-solarized",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
		let react_jsx_runtime = require("react/jsx-runtime");
		let _react = require("react");
		let _runtime_client = require("@deepseek-ai/dsh-client-runtime/client");

		//#region dsh-solarized: definitions
		/** The settings row's locale namespace. */
		const SETTINGS_NS = "settings.solarized";
		/** localStorage key holding the selected theme id. */
		const STORAGE_KEY = "dsh-solarized:theme";
		/** Sentinel meaning "no custom theme — follow the built-in appearance". */
		const DEFAULT_THEME = "system";

		/**
		 * The four curated themes. Each is a third-party theme for the built-in
		 * ThemeRuntime: an id, the base palette it builds on (colorScheme drives
		 * body[data-ds-dark-theme]), and token overrides applied as inline
		 * custom properties on <body> by ui-layout's ThemePresenter. Values are
		 * concrete colors (no var() indirection); the --shiki-* entries restore
		 * the canonical Solarized/Selenized code palette in markdown code blocks.
		 */
		const THEMES = [
	{
		id: "solarized-dark",
		colorScheme: "dark",
		tokens: {
			"--dsw-alias-bg-base": "#002b36",
			"--dsw-alias-bg-layer-1": "#073642",
			"--dsw-alias-bg-layer-2": "#17414c",
			"--dsw-alias-bg-layer-3": "#234a54",
			"--dsw-alias-bg-mask-1": "rgba(0, 0, 0, 0.5)",
			"--dsw-alias-bg-mask-2": "rgba(0, 0, 0, 0.2)",
			"--dsw-alias-bg-mask-3": "rgba(0, 0, 0, 0.48)",
			"--dsw-alias-bg-mask-photo": "rgba(0, 0, 0, 0.88)",
			"--dsw-alias-bg-module-platform": "#04313c",
			"--dsw-alias-bg-multi-select": "#133e4a",
			"--dsw-alias-bg-overlay": "#1f4751",
			"--dsw-alias-bg-skeleton": "rgba(255, 255, 255, 0.08)",
			"--dsw-alias-border-inverted": "rgba(255, 255, 255, 0.06)",
			"--dsw-alias-border-inverted2": "rgba(255, 255, 255, 0.08)",
			"--dsw-alias-border-l1": "rgba(147, 161, 161, 0.14)",
			"--dsw-alias-border-l2-darkmode-thin": "rgba(147, 161, 161, 0.14)",
			"--dsw-alias-border-l2": "rgba(147, 161, 161, 0.26)",
			"--dsw-alias-border-l3": "rgba(147, 161, 161, 0.36)",
			"--dsw-alias-border-l4": "rgba(147, 161, 161, 0.5)",
			"--dsw-alias-brand-primary-invert": "#fdf6e3",
			"--dsw-alias-brand-primary-new-colorprimary-new-color": "#268bd2",
			"--dsw-alias-brand-primary": "#268bd2",
			"--dsw-alias-brand-text": "#ffffff",
			"--dsw-alias-button-contrast-fill": "#586e75",
			"--dsw-alias-button-elevated-fill": "#04313c",
			"--dsw-alias-button-floating-fill": "#133e4a",
			"--dsw-alias-button-floating-hover": "#133e4a",
			"--dsw-alias-button-ghost-active-border": "rgba(131, 148, 150, 0.4)",
			"--dsw-alias-button-ghost-active-fill": "#17414c",
			"--dsw-alias-button-ghost-active-hover": "#1e4650",
			"--dsw-alias-button-info-fill": "#2aa198",
			"--dsw-alias-button-info-hover": "#44a19a",
			"--dsw-alias-button-primary-dimmed": "#17414c",
			"--dsw-alias-button-primary-fill": "#268bd2",
			"--dsw-alias-button-primary-hover": "#4191c6",
			"--dsw-alias-button-tool-bar-fill": "rgba(88, 110, 117, 0.5)",
			"--dsw-alias-button-tool-bar-fill-invisible": "rgba(88, 110, 117, 0.36)",
			"--dsw-alias-button-tool-bar-hover": "rgba(88, 110, 117, 0.6)",
			"--dsw-alias-interactive-bg-active": "rgba(38, 139, 210, 0.2)",
			"--dsw-alias-interactive-bg-hover-accent": "rgba(38, 139, 210, 0.28)",
			"--dsw-alias-interactive-bg-hover-danger": "rgba(220, 50, 47, 0.15)",
			"--dsw-alias-interactive-bg-hover-solid": "#1b444f",
			"--dsw-alias-interactive-bg-hover": "rgba(38, 139, 210, 0.12)",
			"--dsw-alias-label-caption": "#586e75",
			"--dsw-alias-label-dimmed": "#586e75",
			"--dsw-alias-label-primary-bluish": "#789cad",
			"--dsw-alias-label-primary-dimmed": "#8b9b9c",
			"--dsw-alias-label-primary-foreground": "#002b36",
			"--dsw-alias-label-primary-inverted": "#002b36",
			"--dsw-alias-label-primary": "#93a1a1",
			"--dsw-alias-label-secondary": "#839496",
			"--dsw-alias-label-tertiary": "#657b83",
			"--dsw-alias-markdown-citation": "#1b444f",
			"--dsw-alias-markdown-code-block-banner": "#04323d",
			"--dsw-alias-markdown-code-block": "#00252e",
			"--dsw-alias-markdown-code-segment-selected": "#133e4a",
			"--dsw-alias-markdown-code-segment-unselected": "#0d3a46",
			"--dsw-alias-markdown-inline-code": "#073642",
			"--dsw-alias-markdown-placeholder": "#04313c",
			"--dsw-alias-markdown-tag": "#133e4a",
			"--dsw-alias-scrollbar-bg-l1": "#17414c",
			"--dsw-alias-scrollbar-bg-l2": "#1e4650",
			"--dsw-alias-scrollbar-hover-l1": "#2b4f59",
			"--dsw-alias-scrollbar-hover-l2": "#30525c",
			"--dsw-alias-state-business-primary": "#268bd2",
			"--dsw-alias-state-business-tertiary": "#17414c",
			"--dsw-alias-state-error-primary": "#dc322f",
			"--dsw-alias-state-error-secondary": "#ca4e4c",
			"--dsw-alias-state-success-primary": "#859900",
			"--dsw-alias-state-success-secondary": "#899b30",
			"--dsw-alias-state-success-tertiary": "#1a4538",
			"--dsw-alias-state-warn-label": "#b58900",
			"--dsw-alias-state-warn-primary": "#ae8e20",
			"--dsw-alias-state-warn-secondary": "#a99138",
			"--dsw-alias-state-warn-tertiary": "#1c403a",
			"--dsw-alias-toast-bg": "#1b444f",
			"--dsw-alias-tooltip-bg": "#234a54",
			"--dsw-specific-bubble": "#0a3f50",
			"--dsw-specific-bubble-highlight": "#0e4962",
			"--dsw-specific-input-major": "#073642",
			"--dsw-specific-login-input": "#0d3a46",
			"--dsw-specific-menu": "#234a54",
			"--dsw-specific-selector": "#0d3a46",
			"--dsw-specific-sidebar-fill": "#002b36",
			"--dsw-specific-sidebar-nav-item-active-accent": "#10506d",
			"--dsw-specific-sidebar-nav-item-active": "#1b444f",
			"--dsw-specific-sidebar-nav-item-hover": "#04323d",
			"--dsw-specific-tip": "#04313c",
			"--shiki-foreground": "#839496",
			"--shiki-background": "#00252e",
			"--shiki-token-constant": "#2aa198",
			"--shiki-token-string": "#2aa198",
			"--shiki-token-comment": "#586e75",
			"--shiki-token-keyword": "#859900",
			"--shiki-token-parameter": "#cb4b16",
			"--shiki-token-function": "#268bd2",
			"--shiki-token-string-expression": "#2aa198",
			"--shiki-token-punctuation": "#657b83",
			"--shiki-token-link": "#6c71c4",
		}
	},
	{
		id: "solarized-light",
		colorScheme: "light",
		tokens: {
			"--dsw-alias-bg-base": "#fdf6e3",
			"--dsw-alias-bg-layer-1": "#eee8d5",
			"--dsw-alias-bg-layer-2": "#e3dfcf",
			"--dsw-alias-bg-layer-3": "#dad8ca",
			"--dsw-alias-bg-mask-1": "rgba(0, 0, 0, 0.24)",
			"--dsw-alias-bg-mask-2": "rgba(0, 0, 0, 0.12)",
			"--dsw-alias-bg-mask-3": "rgba(0, 0, 0, 0.48)",
			"--dsw-alias-bg-mask-photo": "rgba(0, 0, 0, 0.88)",
			"--dsw-alias-bg-module-platform": "#f6efdc",
			"--dsw-alias-bg-multi-select": "#e7e2d1",
			"--dsw-alias-bg-overlay": "#dedbcc",
			"--dsw-alias-bg-skeleton": "rgba(0, 0, 0, 0.04)",
			"--dsw-alias-border-inverted": "rgba(0, 0, 0, 0)",
			"--dsw-alias-border-inverted2": "rgba(0, 0, 0, 0)",
			"--dsw-alias-border-l1": "rgba(101, 123, 131, 0.14)",
			"--dsw-alias-border-l2-darkmode-thin": "rgba(101, 123, 131, 0.2)",
			"--dsw-alias-border-l2": "rgba(101, 123, 131, 0.22)",
			"--dsw-alias-border-l3": "rgba(101, 123, 131, 0.32)",
			"--dsw-alias-border-l4": "rgba(101, 123, 131, 0.45)",
			"--dsw-alias-brand-primary-invert": "#002b36",
			"--dsw-alias-brand-primary-new-colorprimary-new-color": "#268bd2",
			"--dsw-alias-brand-primary": "#268bd2",
			"--dsw-alias-brand-text": "#ffffff",
			"--dsw-alias-button-contrast-fill": "#93a1a1",
			"--dsw-alias-button-elevated-fill": "#fefbf4",
			"--dsw-alias-button-floating-fill": "#fefbf4",
			"--dsw-alias-button-floating-hover": "#fefaee",
			"--dsw-alias-button-ghost-active-border": "rgba(101, 123, 131, 0.35)",
			"--dsw-alias-button-ghost-active-fill": "#dedbcc",
			"--dsw-alias-button-ghost-active-hover": "#d7d6c8",
			"--dsw-alias-button-info-fill": "#2aa198",
			"--dsw-alias-button-info-hover": "#5fb6ab",
			"--dsw-alias-button-primary-dimmed": "#e3dfcf",
			"--dsw-alias-button-primary-fill": "#268bd2",
			"--dsw-alias-button-primary-hover": "#4d9ed5",
			"--dsw-alias-button-tool-bar-fill": "rgba(101, 123, 131, 0.5)",
			"--dsw-alias-button-tool-bar-fill-invisible": "rgba(101, 123, 131, 0.36)",
			"--dsw-alias-button-tool-bar-hover": "rgba(101, 123, 131, 0.6)",
			"--dsw-alias-interactive-bg-active": "rgba(38, 139, 210, 0.16)",
			"--dsw-alias-interactive-bg-hover-accent": "rgba(38, 139, 210, 0.22)",
			"--dsw-alias-interactive-bg-hover-danger": "rgba(220, 50, 47, 0.06)",
			"--dsw-alias-interactive-bg-hover-solid": "#e3dfcf",
			"--dsw-alias-interactive-bg-hover": "rgba(38, 139, 210, 0.1)",
			"--dsw-alias-label-caption": "#657b83",
			"--dsw-alias-label-dimmed": "#d3d3c5",
			"--dsw-alias-label-primary-bluish": "#517283",
			"--dsw-alias-label-primary-dimmed": "#74888d",
			"--dsw-alias-label-primary-foreground": "#fdf6e3",
			"--dsw-alias-label-primary-inverted": "#fdf6e3",
			"--dsw-alias-label-primary": "#586e75",
			"--dsw-alias-label-secondary": "#657b83",
			"--dsw-alias-label-tertiary": "#839496",
			"--dsw-alias-markdown-citation": "#e3dfcf",
			"--dsw-alias-markdown-code-block-banner": "#e5e1d0",
			"--dsw-alias-markdown-code-block": "#e9e4d2",
			"--dsw-alias-markdown-code-segment-selected": "#fefbf4",
			"--dsw-alias-markdown-code-segment-unselected": "#e3dfcf",
			"--dsw-alias-markdown-inline-code": "#e7e2d1",
			"--dsw-alias-markdown-placeholder": "#f6efdc",
			"--dsw-alias-markdown-tag": "#e3dfcf",
			"--dsw-alias-scrollbar-bg-l1": "#dad8ca",
			"--dsw-alias-scrollbar-bg-l2": "#d7d6c8",
			"--dsw-alias-scrollbar-hover-l1": "#cbcdc1",
			"--dsw-alias-scrollbar-hover-l2": "#c5c8be",
			"--dsw-alias-state-business-primary": "#268bd2",
			"--dsw-alias-state-business-tertiary": "#d0dad5",
			"--dsw-alias-state-error-primary": "#dc322f",
			"--dsw-alias-state-error-secondary": "#e66d65",
			"--dsw-alias-state-success-primary": "#859900",
			"--dsw-alias-state-success-secondary": "#a3b039",
			"--dsw-alias-state-success-tertiary": "#e1dfbb",
			"--dsw-alias-state-warn-label": "#ad880d",
			"--dsw-alias-state-warn-primary": "#b58900",
			"--dsw-alias-state-warn-secondary": "#c7a439",
			"--dsw-alias-state-warn-tertiary": "#e7ddbb",
			"--dsw-alias-toast-bg": "#d7d6c8",
			"--dsw-alias-tooltip-bg": "#d3d3c5",
			"--dsw-specific-bubble": "#ecede2",
			"--dsw-specific-bubble-highlight": "#c6d5d4",
			"--dsw-specific-input-major": "#fdf6e3",
			"--dsw-specific-login-input": "#f6efdc",
			"--dsw-specific-menu": "#dad8ca",
			"--dsw-specific-selector": "#f6efdc",
			"--dsw-specific-sidebar-fill": "#eee8d5",
			"--dsw-specific-sidebar-nav-item-active-accent": "#d0dad5",
			"--dsw-specific-sidebar-nav-item-active": "#e3dfcf",
			"--dsw-specific-sidebar-nav-item-hover": "#e9e4d2",
			"--dsw-specific-tip": "#f6efdc",
			"--shiki-foreground": "#586e75",
			"--shiki-background": "#e9e4d2",
			"--shiki-token-constant": "#2aa198",
			"--shiki-token-string": "#2aa198",
			"--shiki-token-comment": "#93a1a1",
			"--shiki-token-keyword": "#859900",
			"--shiki-token-parameter": "#cb4b16",
			"--shiki-token-function": "#268bd2",
			"--shiki-token-string-expression": "#2aa198",
			"--shiki-token-punctuation": "#657b83",
			"--shiki-token-link": "#6c71c4",
		}
	},
	{
		id: "selenized-dark",
		colorScheme: "dark",
		tokens: {
			"--dsw-alias-bg-base": "#181c20",
			"--dsw-alias-bg-layer-1": "#1f252b",
			"--dsw-alias-bg-layer-2": "#283036",
			"--dsw-alias-bg-layer-3": "#3f474f",
			"--dsw-alias-bg-mask-1": "rgba(0, 0, 0, 0.5)",
			"--dsw-alias-bg-mask-2": "rgba(0, 0, 0, 0.2)",
			"--dsw-alias-bg-mask-3": "rgba(0, 0, 0, 0.48)",
			"--dsw-alias-bg-mask-photo": "rgba(0, 0, 0, 0.88)",
			"--dsw-alias-bg-module-platform": "#1c2126",
			"--dsw-alias-bg-multi-select": "#242b31",
			"--dsw-alias-bg-overlay": "#3c444b",
			"--dsw-alias-bg-skeleton": "rgba(255, 255, 255, 0.08)",
			"--dsw-alias-border-inverted": "rgba(255, 255, 255, 0.06)",
			"--dsw-alias-border-inverted2": "rgba(255, 255, 255, 0.08)",
			"--dsw-alias-border-l1": "rgba(173, 188, 188, 0.12)",
			"--dsw-alias-border-l2-darkmode-thin": "rgba(173, 188, 188, 0.12)",
			"--dsw-alias-border-l2": "rgba(173, 188, 188, 0.22)",
			"--dsw-alias-border-l3": "rgba(173, 188, 188, 0.32)",
			"--dsw-alias-border-l4": "rgba(173, 188, 188, 0.45)",
			"--dsw-alias-brand-primary-invert": "#cad8d9",
			"--dsw-alias-brand-primary-new-colorprimary-new-color": "#4695f7",
			"--dsw-alias-brand-primary": "#4695f7",
			"--dsw-alias-brand-text": "#ffffff",
			"--dsw-alias-button-contrast-fill": "#6a737d",
			"--dsw-alias-button-elevated-fill": "#323a41",
			"--dsw-alias-button-floating-fill": "#30383f",
			"--dsw-alias-button-floating-hover": "#353d44",
			"--dsw-alias-button-ghost-active-border": "rgba(173, 188, 188, 0.4)",
			"--dsw-alias-button-ghost-active-fill": "#353d44",
			"--dsw-alias-button-ghost-active-hover": "#3a434a",
			"--dsw-alias-button-info-fill": "#41c7b9",
			"--dsw-alias-button-info-hover": "#63cbc1",
			"--dsw-alias-button-primary-dimmed": "#353d44",
			"--dsw-alias-button-primary-fill": "#4695f7",
			"--dsw-alias-button-primary-hover": "#63a4f0",
			"--dsw-alias-button-tool-bar-fill": "rgba(106, 115, 125, 0.5)",
			"--dsw-alias-button-tool-bar-fill-invisible": "rgba(106, 115, 125, 0.36)",
			"--dsw-alias-button-tool-bar-hover": "rgba(106, 115, 125, 0.6)",
			"--dsw-alias-interactive-bg-active": "rgba(70, 149, 247, 0.2)",
			"--dsw-alias-interactive-bg-hover-accent": "rgba(70, 149, 247, 0.28)",
			"--dsw-alias-interactive-bg-hover-danger": "rgba(250, 87, 80, 0.15)",
			"--dsw-alias-interactive-bg-hover-solid": "#394148",
			"--dsw-alias-interactive-bg-hover": "rgba(70, 149, 247, 0.12)",
			"--dsw-alias-label-caption": "#6a737d",
			"--dsw-alias-label-dimmed": "#3c444b",
			"--dsw-alias-label-primary-bluish": "#b0cbdf",
			"--dsw-alias-label-primary-dimmed": "#bccacb",
			"--dsw-alias-label-primary-foreground": "#181c20",
			"--dsw-alias-label-primary-inverted": "#181c20",
			"--dsw-alias-label-primary": "#cad8d9",
			"--dsw-alias-label-secondary": "#adbcbc",
			"--dsw-alias-label-tertiary": "#6a737d",
			"--dsw-alias-markdown-citation": "#353d44",
			"--dsw-alias-markdown-code-block-banner": "#1c2126",
			"--dsw-alias-markdown-code-block": "#14181b",
			"--dsw-alias-markdown-code-segment-selected": "#323a41",
			"--dsw-alias-markdown-code-segment-unselected": "#1b2024",
			"--dsw-alias-markdown-inline-code": "#1f252b",
			"--dsw-alias-markdown-placeholder": "#1c2126",
			"--dsw-alias-markdown-tag": "#323a41",
			"--dsw-alias-scrollbar-bg-l1": "#323a41",
			"--dsw-alias-scrollbar-bg-l2": "#353d44",
			"--dsw-alias-scrollbar-hover-l1": "#424b52",
			"--dsw-alias-scrollbar-hover-l2": "#464e56",
			"--dsw-alias-state-business-primary": "#4695f7",
			"--dsw-alias-state-business-tertiary": "#2d3f53",
			"--dsw-alias-state-error-primary": "#fa5750",
			"--dsw-alias-state-error-secondary": "#ee7772",
			"--dsw-alias-state-success-primary": "#75b938",
			"--dsw-alias-state-success-secondary": "#8fc268",
			"--dsw-alias-state-success-tertiary": "#344536",
			"--dsw-alias-state-warn-label": "#dbb32d",
			"--dsw-alias-state-warn-primary": "#dbb32d",
			"--dsw-alias-state-warn-secondary": "#d6be61",
			"--dsw-alias-state-warn-tertiary": "#434435",
			"--dsw-alias-toast-bg": "#394148",
			"--dsw-alias-tooltip-bg": "#3f474f",
			"--dsw-specific-bubble": "#23303f",
			"--dsw-specific-bubble-highlight": "#29415e",
			"--dsw-specific-input-major": "#1f252b",
			"--dsw-specific-login-input": "#1b2024",
			"--dsw-specific-menu": "#3f474f",
			"--dsw-specific-selector": "#1b2024",
			"--dsw-specific-sidebar-fill": "#181c20",
			"--dsw-specific-sidebar-nav-item-active-accent": "#2e445d",
			"--dsw-specific-sidebar-nav-item-active": "#353d44",
			"--dsw-specific-sidebar-nav-item-hover": "#1c2127",
			"--dsw-specific-tip": "#1c2126",
			"--shiki-foreground": "#adbcbc",
			"--shiki-background": "#14181b",
			"--shiki-token-constant": "#41c7b9",
			"--shiki-token-string": "#75b938",
			"--shiki-token-comment": "#6a737d",
			"--shiki-token-keyword": "#8677cf",
			"--shiki-token-parameter": "#ed8649",
			"--shiki-token-function": "#4695f7",
			"--shiki-token-string-expression": "#75b938",
			"--shiki-token-punctuation": "#6a737d",
			"--shiki-token-link": "#dbb32d",
		}
	},
	{
		id: "selenized-light",
		colorScheme: "light",
		tokens: {
			"--dsw-alias-bg-base": "#fbf3db",
			"--dsw-alias-bg-layer-1": "#f5edd6",
			"--dsw-alias-bg-layer-2": "#e6e0cc",
			"--dsw-alias-bg-layer-3": "#d9d5c4",
			"--dsw-alias-bg-mask-1": "rgba(0, 0, 0, 0.24)",
			"--dsw-alias-bg-mask-2": "rgba(0, 0, 0, 0.12)",
			"--dsw-alias-bg-mask-3": "rgba(0, 0, 0, 0.48)",
			"--dsw-alias-bg-mask-photo": "rgba(0, 0, 0, 0.88)",
			"--dsw-alias-bg-module-platform": "#f8f0d9",
			"--dsw-alias-bg-multi-select": "#f2ead3",
			"--dsw-alias-bg-overlay": "#ddd9c6",
			"--dsw-alias-bg-skeleton": "rgba(0, 0, 0, 0.04)",
			"--dsw-alias-border-inverted": "rgba(0, 0, 0, 0)",
			"--dsw-alias-border-inverted2": "rgba(0, 0, 0, 0)",
			"--dsw-alias-border-l1": "rgba(83, 103, 109, 0.12)",
			"--dsw-alias-border-l2-darkmode-thin": "rgba(83, 103, 109, 0.18)",
			"--dsw-alias-border-l2": "rgba(83, 103, 109, 0.22)",
			"--dsw-alias-border-l3": "rgba(83, 103, 109, 0.32)",
			"--dsw-alias-border-l4": "rgba(83, 103, 109, 0.45)",
			"--dsw-alias-brand-primary-invert": "#fbf3db",
			"--dsw-alias-brand-primary-new-colorprimary-new-color": "#0072d4",
			"--dsw-alias-brand-primary": "#0072d4",
			"--dsw-alias-brand-text": "#ffffff",
			"--dsw-alias-button-contrast-fill": "#53676d",
			"--dsw-alias-button-elevated-fill": "#fdf9ed",
			"--dsw-alias-button-floating-fill": "#fdf9ed",
			"--dsw-alias-button-floating-hover": "#fcf7e6",
			"--dsw-alias-button-ghost-active-border": "rgba(83, 103, 109, 0.35)",
			"--dsw-alias-button-ghost-active-fill": "#ddd9c6",
			"--dsw-alias-button-ghost-active-hover": "#dcd8c6",
			"--dsw-alias-button-info-fill": "#009c8f",
			"--dsw-alias-button-info-hover": "#32ad9e",
			"--dsw-alias-button-primary-dimmed": "#e6e0cc",
			"--dsw-alias-button-primary-fill": "#0072d4",
			"--dsw-alias-button-primary-hover": "#2685d5",
			"--dsw-alias-button-tool-bar-fill": "rgba(83, 103, 109, 0.4)",
			"--dsw-alias-button-tool-bar-fill-invisible": "rgba(83, 103, 109, 0.3)",
			"--dsw-alias-button-tool-bar-hover": "rgba(83, 103, 109, 0.5)",
			"--dsw-alias-interactive-bg-active": "rgba(0, 114, 212, 0.16)",
			"--dsw-alias-interactive-bg-hover-accent": "rgba(0, 114, 212, 0.22)",
			"--dsw-alias-interactive-bg-hover-danger": "rgba(210, 33, 45, 0.06)",
			"--dsw-alias-interactive-bg-hover-solid": "#e6e0cc",
			"--dsw-alias-interactive-bg-hover": "rgba(0, 114, 212, 0.1)",
			"--dsw-alias-label-caption": "#909995",
			"--dsw-alias-label-dimmed": "#d9d5c4",
			"--dsw-alias-label-primary-bluish": "#315366",
			"--dsw-alias-label-primary-dimmed": "#475a60",
			"--dsw-alias-label-primary-foreground": "#fbf3db",
			"--dsw-alias-label-primary-inverted": "#fbf3db",
			"--dsw-alias-label-primary": "#3a4d53",
			"--dsw-alias-label-secondary": "#53676d",
			"--dsw-alias-label-tertiary": "#909995",
			"--dsw-alias-markdown-citation": "#e6e0cc",
			"--dsw-alias-markdown-code-block-banner": "#ebe5d0",
			"--dsw-alias-markdown-code-block": "#efe8d2",
			"--dsw-alias-markdown-code-segment-selected": "#fdf9ed",
			"--dsw-alias-markdown-code-segment-unselected": "#e9e3ce",
			"--dsw-alias-markdown-inline-code": "#f2ead3",
			"--dsw-alias-markdown-placeholder": "#f8f0d9",
			"--dsw-alias-markdown-tag": "#e9e3ce",
			"--dsw-alias-scrollbar-bg-l1": "#dcd8c6",
			"--dsw-alias-scrollbar-bg-l2": "#d9d5c4",
			"--dsw-alias-scrollbar-hover-l1": "#cdcbbc",
			"--dsw-alias-scrollbar-hover-l2": "#c8c7b9",
			"--dsw-alias-state-business-primary": "#0072d4",
			"--dsw-alias-state-business-tertiary": "#d8ded6",
			"--dsw-alias-state-error-primary": "#d2212d",
			"--dsw-alias-state-error-secondary": "#de6061",
			"--dsw-alias-state-success-primary": "#489100",
			"--dsw-alias-state-success-secondary": "#7eae42",
			"--dsw-alias-state-success-tertiary": "#e0e2bc",
			"--dsw-alias-state-warn-label": "#ad8900",
			"--dsw-alias-state-warn-primary": "#ad8900",
			"--dsw-alias-state-warn-secondary": "#c1a437",
			"--dsw-alias-state-warn-tertiary": "#ece1bc",
			"--dsw-alias-toast-bg": "#dcd8c6",
			"--dsw-alias-tooltip-bg": "#d9d5c4",
			"--dsw-specific-bubble": "#ecebdb",
			"--dsw-specific-bubble-highlight": "#c4d4d6",
			"--dsw-specific-input-major": "#fbf3db",
			"--dsw-specific-login-input": "#f8f0d9",
			"--dsw-specific-menu": "#d9d5c4",
			"--dsw-specific-selector": "#f8f0d9",
			"--dsw-specific-sidebar-fill": "#f5edd6",
			"--dsw-specific-sidebar-nav-item-active-accent": "#d3dcd6",
			"--dsw-specific-sidebar-nav-item-active": "#e6e0cc",
			"--dsw-specific-sidebar-nav-item-hover": "#efe8d2",
			"--dsw-specific-tip": "#f8f0d9",
			"--shiki-foreground": "#53676d",
			"--shiki-background": "#efe8d2",
			"--shiki-token-constant": "#009c8f",
			"--shiki-token-string": "#489100",
			"--shiki-token-comment": "#909995",
			"--shiki-token-keyword": "#8762c6",
			"--shiki-token-parameter": "#c25d1e",
			"--shiki-token-function": "#0072d4",
			"--shiki-token-string-expression": "#489100",
			"--shiki-token-punctuation": "#909995",
			"--shiki-token-link": "#ad8900",
		}
	},
		];

		/**
		 * Simplified Chinese dictionary (the key-set source of truth). Theme
		 * labels live under "theme.<id>" so the picker cards derive their key
		 * directly from the theme id — no id→key mapping to keep in sync.
		 */
		const zh = {
			"theme.title": "Solarized / Selenized 主题",
			"theme.default": "默认",
			"theme.solarized-dark": "Solarized 深色",
			"theme.solarized-light": "Solarized 浅色",
			"theme.selenized-dark": "Selenized 深色",
			"theme.selenized-light": "Selenized 浅色"
		};

		/** English dictionary, checked complete against the zh key set. */
		const en = {
			"theme.title": "Solarized / Selenized themes",
			"theme.default": "Default",
			"theme.solarized-dark": "Solarized Dark",
			"theme.solarized-light": "Solarized Light",
			"theme.selenized-dark": "Selenized Dark",
			"theme.selenized-light": "Selenized Light"
		};
		//#endregion

		//#region dsh-solarized: persistence
		/** Read a localStorage string value (null on absence or error). */
		function readStorage(key) {
			try {
				const value = window.localStorage.getItem(key);
				return typeof value === "string" ? value : null;
			} catch {
				return null;
			}
		}

		/** Write (or remove with null) a localStorage value. */
		function writeStorage(key, value) {
			try {
				if (value === null) window.localStorage.removeItem(key);
				else window.localStorage.setItem(key, value);
			} catch {
				// storage unavailable / quota — the preference stays process-local
			}
		}

		/** Saved theme id (may be unknown/absent). */
		function readSavedTheme() {
			return readStorage(STORAGE_KEY);
		}

		/** Persist a theme choice; DEFAULT_THEME clears the stored value. */
		function writeSavedTheme(id) {
			writeStorage(STORAGE_KEY, id === DEFAULT_THEME ? null : id);
		}
		//#endregion

		//#region dsh-solarized: settings row store
		/**
		 * Theme row slot store: a mirror of the theme service snapshot. The
		 * plugin's theme/change listener is the only writer; the row component
		 * reads via props.useStore.
		 */
		function createThemeStore() {
			return (0, _runtime_client.defineStore)({
				init: () => ({
					theme: "system",
					revision: -1
				}),
				actions: {
					sync: (d, theme, revision) => {
						if (revision <= d.revision) return;
						d.theme = theme;
						d.revision = revision;
					}
				}
			});
		}
		//#endregion

		//#region dsh-solarized: settings row
		/** Inline style sheet for the row (kept dependency-free). */
		const styles = {
			group: {
				borderBottom: "1px solid var(--dsw-alias-border-l2)",
				display: "flex",
				flexDirection: "column",
				gap: "10px",
				padding: "16px 0"
			},
			title: {
				color: "var(--dsw-alias-label-primary)",
				fontSize: "14px",
				fontWeight: 400,
				lineHeight: "22px"
			},
			grid: {
				display: "flex",
				flexWrap: "wrap",
				gap: "10px"
			},
			card: {
				display: "flex",
				flexDirection: "column",
				alignItems: "center",
				gap: "6px",
				width: "104px",
				padding: "3px",
				borderRadius: "10px",
				border: "2px solid transparent",
				background: "transparent",
				cursor: "pointer",
				font: "inherit",
				boxSizing: "border-box"
			},
			cardSelected: {
				borderColor: "var(--dsw-alias-brand-primary)",
				background: "var(--dsw-alias-interactive-bg-hover)"
			},
			cardLabel: {
				color: "var(--dsw-alias-label-secondary)",
				fontSize: "12px",
				lineHeight: "16px",
				whiteSpace: "nowrap"
			},
			cardLabelSelected: {
				color: "var(--dsw-alias-label-primary)"
			},
			swatch: {
				width: "100%",
				height: "52px",
				borderRadius: "8px",
				boxSizing: "border-box",
				padding: "8px",
				display: "flex",
				flexDirection: "column",
				justifyContent: "center",
				gap: "6px"
			},
			swatchLine: {
				height: "7px",
				borderRadius: "4px"
			},
			defaultSwatch: {
				width: "100%",
				height: "52px",
				borderRadius: "8px",
				boxSizing: "border-box",
				display: "flex",
				overflow: "hidden",
				border: "1px solid var(--dsw-alias-border-l2)"
			}
		};

		/** Mini palette preview driven by one theme's token table. */
		function ThemeSwatch({ tokens }) {
			return (0, react_jsx_runtime.jsxs)("div", {
				style: {
					...styles.swatch,
					background: tokens["--dsw-alias-bg-layer-1"],
					border: "1px solid " + tokens["--dsw-alias-border-l2"]
				},
				children: [
					(0, react_jsx_runtime.jsx)("div", {
						style: {
							...styles.swatchLine,
							width: "70%",
							background: tokens["--dsw-alias-label-primary"],
							opacity: 0.85
						}
					}),
					(0, react_jsx_runtime.jsx)("div", {
						style: {
							...styles.swatchLine,
							width: "45%",
							background: tokens["--dsw-alias-brand-primary"]
						}
					}),
					(0, react_jsx_runtime.jsx)("div", {
						style: {
							...styles.swatchLine,
							width: "55%",
							background: tokens["--dsw-alias-label-secondary"],
							opacity: 0.55
						}
					})
				]
			});
		}

		/** "Default" chip: follow the built-in appearance (light + dark halves). */
		function DefaultSwatch() {
			return (0, react_jsx_runtime.jsxs)("div", {
				style: styles.defaultSwatch,
				children: [
					(0, react_jsx_runtime.jsx)("div", { style: { flex: 1, background: "#f4f4f5" } }),
					(0, react_jsx_runtime.jsx)("div", { style: { flex: 1, background: "#1c1c20" } })
				]
			});
		}

		/** One selectable theme card. */
		function ThemeCard({ theme, selected, onSelect, t }) {
			return (0, react_jsx_runtime.jsxs)("button", {
				type: "button",
				onClick: onSelect,
				"aria-pressed": selected,
				style: {
					...styles.card,
					...(selected ? styles.cardSelected : {})
				},
				children: [
					(0, react_jsx_runtime.jsx)(ThemeSwatch, { tokens: theme.tokens }),
					(0, react_jsx_runtime.jsx)("span", {
						style: {
							...styles.cardLabel,
							...(selected ? styles.cardLabelSelected : {})
						},
						children: t("theme." + theme.id)
					})
				]
			});
		}

		/**
		 * Theme picker row registered into the Settings → General item slot,
		 * right after the built-in Appearance row: title + a "Default" chip and
		 * one swatch card per curated theme.
		 */
		function ThemeRow({ t, setTheme, useStore }) {
			const theme = useStore((s) => s.theme);
			const selected = THEMES.some((candidate) => candidate.id === theme) ? theme : null;
			return (0, react_jsx_runtime.jsxs)("div", {
				style: styles.group,
				children: [
					(0, react_jsx_runtime.jsx)("div", {
						style: styles.title,
						children: t("theme.title")
					}),
					(0, react_jsx_runtime.jsxs)("div", {
						style: styles.grid,
						children: [
							(0, react_jsx_runtime.jsxs)("button", {
								type: "button",
								onClick: () => setTheme(DEFAULT_THEME),
								"aria-pressed": selected === null,
								style: {
									...styles.card,
									...(selected === null ? styles.cardSelected : {})
								},
								children: [
									(0, react_jsx_runtime.jsx)(DefaultSwatch, {}),
									(0, react_jsx_runtime.jsx)("span", {
										style: {
											...styles.cardLabel,
											...(selected === null ? styles.cardLabelSelected : {})
										},
										children: t("theme.default")
									})
								]
							}),
							THEMES.map((themeDefinition) => (0, react_jsx_runtime.jsx)(ThemeCard, {
								theme: themeDefinition,
								selected: selected === themeDefinition.id,
								onSelect: () => setTheme(themeDefinition.id),
								t
							}, themeDefinition.id))
						]
					})
				]
			});
		}
		//#endregion

		//#region dsh-solarized: client plugin body
		/**
		 * Required services: theme runtime (registration and switching), the
		 * settings slot and locale (the picker row). Persistence is
		 * localStorage, so no settings transport is needed.
		 */
		const inject = [
			"slots",
			"locale",
			"theme"
		];

		/**
		 * Client plugin body: register the four themes into the theme runtime,
		 * restore the saved theme, keep the row store in sync with
		 * theme/change, and register the picker row into Settings → General.
		 * @param ctx - client cordis context.
		 */
		function apply(ctx) {
			const disposers = THEMES.map((themeDefinition) => ctx.theme.register(themeDefinition));
			ctx.effect(() => () => {
				for (const dispose of disposers) dispose();
			}, "dsh-solarized: theme registration");

			// Restore the saved theme once (before any user interaction).
			const saved = readSavedTheme();
			if (typeof saved === "string" && saved !== DEFAULT_THEME && THEMES.some((themeDefinition) => themeDefinition.id === saved)) {
				const current = ctx.theme.getTheme().preference;
				if (current !== saved) ctx.theme.setTheme(saved);
			}

			const themeStore = createThemeStore();
			let themeBound;
			const syncTheme = (snapshot) => {
				themeBound?.sync(snapshot.preference, snapshot.revision);
			};
			ctx.on("theme/change", syncTheme);

			ctx.effect(() => ctx.locale.register(SETTINGS_NS, {
				zh,
				en
			}), "dsh-solarized: settings row dictionaries");

			const themeInjected = (actions) => {
				themeBound = actions;
				syncTheme(ctx.theme.getTheme());
				return {
					setTheme: (id) => {
						ctx.theme.setTheme(id);
						writeSavedTheme(id);
					}
				};
			};
			ctx.slots.inject("settings.general.item", () => ctx.slots.register({
				name: "settings.general.item",
				id: "solarized",
				order: 20,
				store: themeStore,
				locale: SETTINGS_NS,
				inject: themeInjected
			}, ThemeRow));
		}
		//#endregion

		exports.SETTINGS_NS = SETTINGS_NS;
		exports.THEMES = THEMES;
		exports.DEFAULT_THEME = DEFAULT_THEME;
		exports.apply = apply;
		exports.inject = inject;
		return module.exports;
	}
});
